server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/a
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
logging:
  level:
    com.cleansoft.demo.dao: info